# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

def fancy_sign(message, size=40, separator='=-')
  puts ''.center(size, separator)
  puts " #{message} ".center(size * separator.length, separator)
  puts ''.center(size, separator)
end

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    fancy_sign "Would you like to add a Changelog?  Empty for NO"
    changelog = `read changelog; echo $changelog`.chomp

    match(
      type: "appstore",
      git_url: "git@github.com:OTGApps/ProjectCerts.git"
    ) # more information: https://codesigning.guide
    gym(workspace: "Dropzones.xcworkspace", scheme: "Dropzones") # Build your app - more options available
    pilot(changelog: changelog)
  end

  desc "Push a new release build to the App Store"
  lane :release do
    # increment_build_number(xcodeproj: "Dropzones.xcodeproj")
    match(
      type: "appstore",
      git_url: "git@github.com:OTGApps/ProjectCerts.git"
    ) # more information: https://codesigning.guide
    build_app(workspace: "Dropzones.xcworkspace", scheme: "Dropzones")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
