# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :build do |options|
    gradle(task: "clean assembleRelease")
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end

  lane :alpha do |options|
    # gradle(task: "clean assembleRelease")
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store(track:'alpha')
    # supply(
    #   track: "alpha",
    #   apk: options[:apk],
    #   json_key: "../../ProjectCerts/service-accounts/google-play-service-account.json",
    #   package_name: options[:package_name],
    #   skip_upload_metadata: true,
    #   skip_upload_images: true,
    #   skip_upload_screenshots: true
    # )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # gradle(task: "clean bundleRelease")
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    upload_to_play_store
  end
end
