# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to the Google Play Store"
  lane :internal do
    gradle(task: "clean")
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    supply(
      track: 'internal',
      json_key: "../../ProjectCerts/service-accounts/google-play-service-account.json",
      skip_upload_apk: true,
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    )
  end

  desc "Submit a new Production Build to the Google Play Store"
  lane :production do
    release_the_hounds = prompt(
      boolean: true,
      text: "Are you sure you want to do a production release? Think long and hard about this before answering.",
    )

    if release_the_hounds
      gradle(task: "clean")
      gradle(
        task: "bundle",
        build_type: "Release"
      )

      supply(
        track: production,
        json_key: "../../ProjectCerts/service-accounts/google-play-service-account.json",
        skip_upload_apk: true,
        aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
      )
    end
  end
end